"use client";

import "@/sass/main.scss";
import "./i18n";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

// export const metadata = {
//   title: "Maven Group",
//   description: "Generated by create next app",
//   icons: {
//     icon: ["/favicon.ico?v=4"],
//     apple: ["/apple-touch-icon.png?v=4"],
//     shortcut: ["/apple-touch-icon.png"],
//   },
//   webmanifest: "site/webmanifest.json",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Bruno+Ace&family=Comfortaa:wght@300;400;500;600;700&family=Lato&family=Montserrat:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="page">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
